### ISSUE TITLE
Error when trying to install the toolkit

### ISSUE THREAD

**Issue by nashvan** [sinaahmadi/klpt#17]
Hi Kake @sinaahmadi , do you mind if you can check what I am I missing 
```
nashwan@Nashwan:~/Desktop/klpt/klpt$ pip install klpt
WARNING: Executing a script that is loading libcrypto in an unsafe way. This will fail in a future version of macOS. Set the LIBRESSL_REDIRECT_STUB_ABORT=1 in the environment to force this into an error.
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting klpt
From cffi callback <function _verify_callback at 0x10468bed8>:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/OpenSSL/SSL.py", line 309, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)': /simple/klpt/
From cffi callback <function _verify_callback at 0x10468bd70>:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/OpenSSL/SSL.py", line 309, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)': /simple/klpt/
From cffi callback <function _verify_callback at 0x1046d41b8>:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/OpenSSL/SSL.py", line 309, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)': /simple/klpt/
From cffi callback <function _verify_callback at 0x1046d4668>:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/OpenSSL/SSL.py", line 309, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)': /simple/klpt/
From cffi callback <function _verify_callback at 0x1046d4938>:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/OpenSSL/SSL.py", line 309, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)': /simple/klpt/
From cffi callback <function _verify_callback at 0x1046d42a8>:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/OpenSSL/SSL.py", line 309, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  Could not fetch URL https://pypi.org/simple/klpt/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/klpt/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)) - skipping
  ERROR: Could not find a version that satisfies the requirement klpt (from versions: none)
ERROR: No matching distribution found for klpt
From cffi callback <function _verify_callback at 0x10470bd70>:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/OpenSSL/SSL.py", line 309, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)) - skipping
```

**Comment by nashvan** [comment]
@sinaahmadi thank for the reply, do you mind to share one example of the command that can run the tool? I am struggling to make it run, I am sure I must be missing an argument or such for the command I am using, I tried multiple options:

```
python setup.py import klpt dialect sorani script "Arabic" numeral ١٢٣٤٥٦٧٨٩٠
```

**Comment by sinaahmadi** [comment]
There are two ways to run Python:

1. When opening your Terminal/command line, type `python` and enter. This will change the environment from bash to Python. Then, write your Python code. This is handy for quick tasks where reusing the code is not a priority.
2. Create a file with the `.py` extension. Then, write your Python code inside. Then, from your command line/Terminal, run the file as `python my_file.py`.

Find more at https://realpython.com/run-python-scripts/

**Comment by nashvan** [comment]
@sinaahmadi thabks for your reply, but thats really not what i am after I know very well how to run python scripts. My question is very specific to your tool and what are the arguments need to passed to when running your tool. But all good dont worry will try to reverse engineer your tool and figure out whats needs to be passed to.

**Comment by sinaahmadi** [comment]
I guess you should note that KLPT is a toolkit, not a script. So, I'm afraid there is no argument to be passed to run it through the command line!
